//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiviApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KiviApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laske pisteet.
        /// </summary>
        internal static string CalculatePoints {
            get {
                return ResourceManager.GetString("CalculatePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyhjennä pelilauta.
        /// </summary>
        internal static string ClearGameBoard {
            get {
                return ResourceManager.GetString("ClearGameBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulje.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esimerkki pisteiden laskusta.
        /// </summary>
        internal static string ExampleTitle {
            get {
                return ResourceManager.GetString("ExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelilauta on tyhjä!
        ///Kosketa pelilaudan ruutuja lisätäksesi kiviä..
        /// </summary>
        internal static string GameboardEmpty {
            get {
                return ResourceManager.GetString("GameboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaihtoehtoiset ikonit kiville:.
        /// </summary>
        internal static string IconsChange {
            get {
                return ResourceManager.GetString("IconsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisteiden laskeminen.
        /// </summary>
        internal static string InfoButtonText {
            get {
                return ResourceManager.GetString("InfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisteiden lasku.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yksittäisistä kivistä saa pisteitä sen ruudun mukaan, jossa kivi on:
        ///
        ///- Punainen ruutu on 3 pisteen arvoinen
        ///- Musta ruutu on 2 pisteen arvoinen
        ///- Valkoinen ruutu on 1 pisteen arvoinen
        ///
        ///Yhtenäisten ketjujen pisteet lasketaan siten, että ketjun kivien yhteispisteet kerrotaan ketjuun kuuluvien kivien määrällä. Ketjuja voi muodostua joko pysty- tai vaakasuoraan eli jotkut kivet voivat tuoda pisteitä kahdesti..
        /// </summary>
        internal static string InstructionsPart1 {
            get {
                return ResourceManager.GetString("InstructionsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vihreän pelaajan pisteet:.
        /// </summary>
        internal static string InstructionsPart2 {
            get {
                return ResourceManager.GetString("InstructionsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaakaan kivet 1+2+3 = 6,
        ///ketju yht. 6x3 = 18.
        /// </summary>
        internal static string InstructionsPart3 {
            get {
                return ResourceManager.GetString("InstructionsPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaakaan kivet 3+2 = 5,
        ///ketju yht. 5x2 = 10.
        /// </summary>
        internal static string InstructionsPart4 {
            get {
                return ResourceManager.GetString("InstructionsPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pystyyn kivet 2+1+2 = 5,
        ///ketju yht. 5x3 = 15.
        /// </summary>
        internal static string InstructionsPart5 {
            get {
                return ResourceManager.GetString("InstructionsPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pystyyn kivet 2+3 = 5,
        ///ketju yht. 5x2 = 10.
        /// </summary>
        internal static string InstructionsPart6 {
            get {
                return ResourceManager.GetString("InstructionsPart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yksittäiset kivet 1+2 = 3.
        /// </summary>
        internal static string InstructionsPart7 {
            get {
                return ResourceManager.GetString("InstructionsPart7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisteet yhteensä = 56.
        /// </summary>
        internal static string InstructionsPart8 {
            get {
                return ResourceManager.GetString("InstructionsPart8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohita aloitusanimaatiot:.
        /// </summary>
        internal static string IntroChange {
            get {
                return ResourceManager.GetString("IntroChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
